pm: a8k: fix compilation error when PM_TRACE_ENABLE is defined
Move plat_my_core_pos into the trace define.

Change-Id: I615277c0141e4f7e9c1729c6ec82f035f9533783
Signed-off-by: Igal Liberman <igall@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/41861
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
Reviewed-by: Kostya Porotchkin <kostap@marvell.com>